server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.1.155
                port: 5672
                username: qfy
                password: qiaofeiyu123
      bindings: #服务的整合处理
        output: #通道的名称
          destination: studyExchange #表示要使用的Exchange的名称
          content-type: application/json #表示消息类型，本次为json，文本则设置text/plain
          binder: {defaultRabbit} #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #设置间隔时间
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔
    instance-id: send-8801.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问路径变为ip地址