server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 8080
        #默认8719端口，如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719
        clientIp: 192.168.1.124:8401

      eager: true


management:
  endpoint:
    sentinel:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'